# Generated by Django 2.1 on 2020-01-18 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=256, null=True, upload_to='img/posts', verbose_name='Изображение')),
                ('commets', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('like_count', models.PositiveIntegerField(verbose_name='Количество лайков')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 1, 18, 8, 51, 48, 418629, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to='img/avatars', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tape.User', verbose_name='Автор'),
        ),
    ]
