# Generated by Django 3.0.1 on 2020-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0004_auto_20200119_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
