# Generated by Django 3.0.1 on 2020-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0005_auto_20200119_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
